# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperTaxi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperTaxi
	
	pod 'Alamofire', '~> 3.4'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'AlamofireImage', '~> 2.0' 
	pod 'AlamofireObjectMapper', '~> 3.0'
	pod 'IQKeyboardManagerSwift'
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'googleplus-ios-sdk'
	pod 'ImageLoader'
	pod 'SWRevealViewController', '~> 2.3'

  target 'SuperTaxiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuperTaxiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
