# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperTaxi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperTaxi
	
	pod 'Alamofire', '~> 4.3'
	pod 'SwiftyJSON'
	pod 'AlamofireImage', '~> 3.1' 
	pod 'AlamofireObjectMapper', '~> 4.0'
	pod 'IQKeyboardManagerSwift', '4.0.6'
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'ImageLoader', '~> 0.1.1'
	pod 'SWRevealViewController', '~> 2.3'
	pod 'Google/SignIn'

  target 'SuperTaxiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuperTaxiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
